//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBQ1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CBQ_Entities : DbContext
    {
        public CBQ_Entities()
            : base("name=CBQ_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin_tbl> Admin_tbl { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Register_login> Register_login { get; set; }
    }
}
